Add support for Azure Clouds

diff --git a/tests_e2e/pipeline/pipeline.yml b/tests_e2e/pipeline/pipeline.yml
--- a/tests_e2e/pipeline/pipeline.yml
+++ b/tests_e2e/pipeline/pipeline.yml
@@ -71,7 +71,23 @@ jobs:
 
       # Extract the Azure cloud from the "connection_info" variable and store it in the "cloud" variable.
       # The cloud name is used as a suffix of the value for "connection_info" and comes after the last '-'.
-      - bash: echo "##vso[task.setvariable variable=cloud]$(echo $CONNECTION_INFO | sed 's/^.*-//')"
+      - bash:
+      - bash: |
+          case $(echo $CONNECTION_INFO | sed 's/^.*-//') in
+              public)
+                  echo "##vso[task.setvariable variable=cloud]AzureCloud"
+                  ;;
+              china)
+                  echo "##vso[task.setvariable variable=cloud]AzureChinaCloud"
+                  ;;
+              government)
+                  echo "##vso[task.setvariable variable=cloud]AzureUSGovernment"
+                  ;;
+              *)
+                  echo "Invalid CONNECTION_INFO: $CONNECTION_INFO" >&2
+                  exit 1
+                  ;;
+          esac
         displayName: "Set Cloud type"
 
       - task: DownloadSecureFile@1
