ubuntu20

diff --git a/.github/workflows/ci_pr.yml b/.github/workflows/ci_pr.yml
--- a/.github/workflows/ci_pr.yml
+++ b/.github/workflows/ci_pr.yml
@@ -14,14 +14,14 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - python-version: 2.6
+#          - python-version: 2.6
           - python-version: 2.7
-          - python-version: 3.4
+#          - python-version: 3.4
 
     name: "Python ${{ matrix.python-version }} Unit Tests"
     runs-on: ubuntu-20.04
     container:
-      image: ubuntu:16.04
+      image: ubuntu:20.04
       volumes:
         - /home/waagent:/home/waagent
     defaults:
@@ -53,79 +53,79 @@ jobs:
         ./ci/nosetests.sh
         exit $?
 
-  test-current-python-versions:
-
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-#          py27 version no longer supported by github build runners. So disabling it until fix is found.
-#          - python-version: 2.7
-#            PYLINTOPTS: "--rcfile=ci/2.7.pylintrc --ignore=tests_e2e,makepkg.py"
-
-          - python-version: 3.5
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e,makepkg.py"
-
-          - python-version: 3.6
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
-
-          - python-version: 3.7
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
-
-          - python-version: 3.8
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
-
-          - python-version: 3.9
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc"
-            additional-nose-opts: "--with-coverage --cover-erase --cover-inclusive --cover-branches --cover-package=azurelinuxagent"
-
-    name: "Python ${{ matrix.python-version }} Unit Tests"
-    runs-on: ubuntu-20.04
-
-    env:
-      PYLINTOPTS: ${{ matrix.PYLINTOPTS }}
-      PYLINTFILES: "azurelinuxagent setup.py makepkg.py tests tests_e2e"
-      NOSEOPTS: "--with-timer ${{ matrix.additional-nose-opts }}"
-      PYTHON_VERSION: ${{ matrix.python-version }}
-
-    steps:
-
-    - name: Checkout WALinuxAgent repo
-      uses: actions/checkout@v3
-
-    - name: Setup Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
-
-    - name: Install dependencies
-      id: install-dependencies
-      run: |
-        sudo env "PATH=$PATH" python -m pip install --upgrade pip
-        sudo env "PATH=$PATH" pip install -r requirements.txt
-        sudo env "PATH=$PATH" pip install -r test-requirements.txt
-
-    - name: Run pylint
-      run: |
-        pylint $PYLINTOPTS --jobs=0 $PYLINTFILES
-
-    - name: Test with nosetests
-      if: success() || (failure() && steps.install-dependencies.outcome == 'success')
-      run: |
-        ./ci/nosetests.sh
-        exit $?
-
-    - name: Compile Coverage
-      if: matrix.python-version == 3.9
-      run: |
-        echo looking for coverage files :
-        ls -alh | grep -i coverage
-        sudo env "PATH=$PATH" coverage combine coverage.*.data
-        sudo env "PATH=$PATH" coverage xml
-        sudo env "PATH=$PATH" coverage report
-
-    - name: Upload Coverage
-      if: matrix.python-version == 3.9
-      uses: codecov/codecov-action@v3
-      with:
-        file: ./coverage.xml
+#  test-current-python-versions:
+#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+##          py27 version no longer supported by github build runners. So disabling it until fix is found.
+##          - python-version: 2.7
+##            PYLINTOPTS: "--rcfile=ci/2.7.pylintrc --ignore=tests_e2e,makepkg.py"
+#
+#          - python-version: 3.5
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e,makepkg.py"
+#
+#          - python-version: 3.6
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
+#
+#          - python-version: 3.7
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
+#
+#          - python-version: 3.8
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
+#
+#          - python-version: 3.9
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc"
+#            additional-nose-opts: "--with-coverage --cover-erase --cover-inclusive --cover-branches --cover-package=azurelinuxagent"
+#
+#    name: "Python ${{ matrix.python-version }} Unit Tests"
+#    runs-on: ubuntu-20.04
+#
+#    env:
+#      PYLINTOPTS: ${{ matrix.PYLINTOPTS }}
+#      PYLINTFILES: "azurelinuxagent setup.py makepkg.py tests tests_e2e"
+#      NOSEOPTS: "--with-timer ${{ matrix.additional-nose-opts }}"
+#      PYTHON_VERSION: ${{ matrix.python-version }}
+#
+#    steps:
+#
+#    - name: Checkout WALinuxAgent repo
+#      uses: actions/checkout@v3
+#
+#    - name: Setup Python ${{ matrix.python-version }}
+#      uses: actions/setup-python@v4
+#      with:
+#        python-version: ${{ matrix.python-version }}
+#
+#    - name: Install dependencies
+#      id: install-dependencies
+#      run: |
+#        sudo env "PATH=$PATH" python -m pip install --upgrade pip
+#        sudo env "PATH=$PATH" pip install -r requirements.txt
+#        sudo env "PATH=$PATH" pip install -r test-requirements.txt
+#
+#    - name: Run pylint
+#      run: |
+#        pylint $PYLINTOPTS --jobs=0 $PYLINTFILES
+#
+#    - name: Test with nosetests
+#      if: success() || (failure() && steps.install-dependencies.outcome == 'success')
+#      run: |
+#        ./ci/nosetests.sh
+#        exit $?
+#
+#    - name: Compile Coverage
+#      if: matrix.python-version == 3.9
+#      run: |
+#        echo looking for coverage files :
+#        ls -alh | grep -i coverage
+#        sudo env "PATH=$PATH" coverage combine coverage.*.data
+#        sudo env "PATH=$PATH" coverage xml
+#        sudo env "PATH=$PATH" coverage report
+#
+#    - name: Upload Coverage
+#      if: matrix.python-version == 3.9
+#      uses: codecov/codecov-action@v3
+#      with:
+#        file: ./coverage.xml
